# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# smdk4x12. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that smdk4x12 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

LOCAL_PATH := device/hardkernel/odroidq2

include $(LOCAL_PATH)/BoardConfig.mk

DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay

PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/vold.fstab:system/etc/vold.fstab

#media codec file
PRODUCT_COPY_FILES += \
       device/samsung/smdk4x12/media_codecs.xml:system/etc/media_codecs.xml


#-------------------------------------------------------------------------------------
#
# optional package(LOCAL_MODULE_TAGS := optional) install
#
#-------------------------------------------------------------------------------------
PRODUCT_PACKAGES += \
		sensors.$(TARGET_PRODUCT) \
		logtool \
		libmplmpu \
		libmllite \
		libmlplatform \
		libinvensense_hal 

PRODUCT_COPY_FILES += \
       device/samsung/exynos4/lib/mali_ump/libion.so:system/lib/libion.so

#-------------------------------------------------------------------------------------
#
# ARM Streamline Debugger(DS-5)
#
#-------------------------------------------------------------------------------------
ifeq ($(ENABLE_ARM_STREAMLINE_DEBUGGER), true)

PRODUCT_PACKAGES += \
		gatord

PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/drivers/gator_q.ko:system/lib/modules/gator.ko

endif	

#-------------------------------------------------------------------------------------
#
# WIFI firmware
#
#-------------------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/drivers/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
	device/hardkernel/odroidq2/drivers/bcm4330.cal:system/etc/firmware/bcmdhd.cal \
	device/hardkernel/odroidq2/drivers/bcm4330.hcd:system/etc/firmware/bcmdhd.hcd

PRODUCT_PROPERTY_OVERRIDES += \
	wifi.interface=wlan0 \
	wifi.supplicant_scan_interval=15
 

BOARD_WLAN_DEVICE_REV 	:= bcm4330_b2
WIFI_BAND             	:= 802_11_ABG

$(call inherit-product-if-exists, hardware/broadcom/wlan/bcmdhd/firmware/bcm4330/device-bcm.mk)

# Init files
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/conf/init.odroidq2.rc:root/init.odroidq2.rc \
	device/hardkernel/odroidq2/conf/init.odroidq2.usb.rc:root/init.odroidq2.usb.rc \

# For V4L2
ifeq ($(BOARD_USE_V4L2), true)
ifeq ($(BOARD_USE_V4L2_ION), true)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/conf/ueventd.odroidq2.v4l2ion.rc:root/ueventd.odroidq2.rc
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/conf/ueventd.odroidq2.v4l2.rc:root/ueventd.odroidq2.rc
endif
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidq2/conf/ueventd.odroidq2.rc:root/ueventd.odroidq2.rc
endif

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/odroid-ts.idc:system/usr/idc/odroidq-ts.idc \
	device/hardkernel/proprietary/bin/odroid-ts.kl:system/usr/keylayout/odroidq-ts.kl \
	device/hardkernel/proprietary/bin/odroid-ts.kcm:system/usr/keylayout/odroidq-ts.kcm \
	device/hardkernel/proprietary/bin/odroid-keypad.kl:system/usr/keylayout/odroid-keypad.kl \
	device/hardkernel/proprietary/bin/odroid-keypad.kcm:system/usr/keychars/odroid-keypad.kcm

# XBox 360 Controller kl keymaps
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/Vendor_045e_Product_0291.kl:system/usr/keylayout/Vendor_045e_Product_0291.kl \
	device/hardkernel/proprietary/bin/Vendor_045e_Product_0719.kl:system/usr/keylayout/Vendor_045e_Product_0719.kl \
	device/hardkernel/proprietary/bin/Vendor_045e_Product_0719.kcm:system/usr/keychars/Vendor_045e_Product_0719.kcm

# Mali
PRODUCT_PACKAGES += \
        libEGL_mali \
        libGLESv1_CM_mali \
        libGLESv2_mali \
        libMali \
        libUMP \
        libion2

# gralloc
PRODUCT_PACKAGES += \
	gralloc.$(TARGET_PRODUCT)

# Filesystem management tools
PRODUCT_PACKAGES += \
	make_ext4fs \
	setup_fs

# audio
PRODUCT_PACKAGES += \
	audio_policy.$(TARGET_PRODUCT) \
	audio.primary.$(TARGET_PRODUCT) \
	audio.a2dp.default \
	libaudioutils
# wenpni.cui: AudioPolicyManager will read this file.
PRODUCT_COPY_FILES += \
        device/samsung/smdk4x12/audio_policy.conf:/system/etc/audio_policy.conf

# ULP Audio
#ifeq ($(USE_ULP_AUDIO),true)
#PRODUCT_PACKAGES += \
#	libaudiohw \
#	MusicULP \
#	libsa_jni
#endif

# ALP Audio
ifeq ($(BOARD_USE_ALP_AUDIO),true)
PRODUCT_PACKAGES += \
	libOMX.SEC.MP3.Decoder
endif

# Camera
PRODUCT_PACKAGES += \
	camera.$(TARGET_PRODUCT)

# SEC_Camera
ifeq ($(USE_SEC_CAMERA),true)
PRODUCT_PACKAGES += \
	SEC_Camera
endif

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libstagefrighthw \
	com.android.future.usb.accessory

# Video Editor
PRODUCT_PACKAGES += \
	VideoEditorGoogle

# Misc other modules
PRODUCT_PACKAGES += \
	lights.$(TARGET_PRODUCT) \
	hwcomposer.$(TARGET_PRODUCT)
#hwcomposer.$(TARGET_BOARD_PLATFORM)

# Widevine DRM
PRODUCT_PACKAGES += com.google.widevine.software.drm.xml \
	com.google.widevine.software.drm \
	WidevineSamplePlayer \
	test-libwvm \
	test-wvdrmplugin \
	test-wvplayer_L1 \
	libdrmwvmplugin \
	libwvm \
	libWVStreamControlAPI_L1 \
	libwvdrm_L1

# OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/media_profiles.xml:system/etc/media_profiles.xml

# OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libSEC_OMX_Resourcemanager \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# hwconvertor modules
PRODUCT_PACKAGES += \
	libhwconverter \

# MFC firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin

# FIMC-IS firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/fimc_is_fw.bin:system/vendor/firmware/fimc_is_fw.bin \
	device/samsung/exynos4/firmware/setfile.bin:system/vendor/firmware/setfile.bin

#-------------------------------------------------------------------------------------
#
# framework permission file
#
#-------------------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
	frameworks/native/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
	frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/native/data/etc/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
	frameworks/native/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
	frameworks/native/data/etc/android.hardware.sensor.barometer.xml:system/etc/permissions/android.hardware.sensor.barometer.xml \
	frameworks/native/data/etc/android.hardware.telephony.cdma.xml:system/etc/permissions/android.hardware.telephony.cdma.xml \
	frameworks/native/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/native/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	frameworks/native/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml \
	frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072

PRODUCT_PROPERTY_OVERRIDES += \
	hwui.render_dirty_regions=false

# Widevine DRM
PRODUCT_PROPERTY_OVERRIDES += \
	drm.service.enabled=true

# Set default USB interface
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
	persist.sys.usb.config=mass_storage

include frameworks/native/build/tablet-dalvik-heap.mk

PRODUCT_CHARACTERISTICS := tablet

PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml

$(call inherit-product, frameworks/native/build/tablet-dalvik-heap.mk)

PRODUCT_AAPT_CONFIG := normal large tvdpi hdpi
PRODUCT_AAPT_PREF_CONFIG := tvdpi

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

PRODUCT_PACKAGES += \
   mbmd \
   gps.$(TARGET_PRODUCT) \
   MbmService \
   libmbm-ril

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/kernel:kernel

## Not the prettiest hack ever, but it'll do until JPlayer is understood
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/../proprietary/etc/98netflix:system/etc/init.d/98netflix

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/apk/Ultra_Explorer.apk:system/app/Ultra_Explorer.apk \
	device/hardkernel/proprietary/apk/jackpal.androidterm.apk:system/app/jackpal.androidterm.apk \
	device/hardkernel/proprietary/lib/libjackpal-androidterm4.so:system/lib/libjackpal-androidterm4.so \
	device/hardkernel/proprietary/apk/com.miian.android.sensors-1.apk:system/app/SensorList.apk

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/apk/DicePlayer.apk:system/app/DicePlayer.apk \
	device/hardkernel/proprietary/lib/libSoundTouch.so:system/lib/libSoundTouch.so \
	device/hardkernel/proprietary/lib/libdice_jb.so:system/lib/libdice_jb.so \
	device/hardkernel/proprietary/lib/libdice_jb2.so:system/lib/libdice_jb2.so \
	device/hardkernel/proprietary/lib/libdice_loadlibrary.so:system/lib/libdice_loadlibrary.so \
	device/hardkernel/proprietary/lib/libdice_software.so:system/lib/libdice_software.so \
	device/hardkernel/proprietary/lib/libdice_software_jb.so:system/lib/libdice_software_jb.so \
	device/hardkernel/proprietary/lib/libffmpeg_dice.so:system/lib/libffmpeg_dice.so \
	device/hardkernel/proprietary/lib/libsonic.so:system/lib/libsonic.so

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/apk/Superuser.apk:system/app/Superuser.apk \
	device/hardkernel/proprietary/bin/su:system/xbin/su

PRODUCT_PACKAGES += \
    OdroidUpdater

# init.d support
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/sysinit:system/bin/sysinit
